version: '3.11'


services:

#  web:
#    build:
#      context: .
#    volumes:
#      - ./:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

  db:
    image: postgres:15
    ports:
      - "30333:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: {}